import { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';

function ModalDisclaimer() {
  const [show, setShow] = useState(true);

  const handleClose = () => setShow(false);

return(

<Modal show={show} onHide={handleClose}
size="lg"
aria-labelledby="contained-modal-title-vcenter"
centered>

        <Modal.Header closeButton>
          <Modal.Title>Disclaimer</Modal.Title>
        </Modal.Header>
        <Modal.Body>This symptom checker is a tool designed to provide you with information and estimate the possibility of certain diseases based on the symptoms you select. However, it is important to note the following:
<p>1.Not a Substitute for Professional Medical Advice: The results provided by this symptom checker are not a substitute for professional medical advice, diagnosis, or treatment. It is recommended to consult with a qualified healthcare professional for an accurate diagnosis.</p>
<p>2.	Limited Scope: Our database currently includes six diseases: common cold, COVID-19, hypothyroidism, polycystic ovary syndrome (PCOS), cluster headache, and migraine. It is not designed to cover all possible health conditions.</p>
<p>3.	Estimates, not Confirmations: The results generated by this tool provide an estimate of the possibility of the included diseases based on the symptoms selected. They do not provide a definitive confirmation of a specific condition.</p>
<p>4.	User Responsibility: It is essential to use this tool responsibly and not solely rely on its results. If you have any concerns about your health or the accuracy of the results, seek professional medical advice.</p>
</Modal.Body>
        <Modal.Footer>
          <Button variant="primary" onClick={handleClose}>
            Close
          </Button>
         
        </Modal.Footer>
      </Modal>
);
}
export default ModalDisclaimer